stages:
  - deploy

deploy_to_server:
  stage: deploy
  tags:
    - deploy
  script:
    - echo "Deploying HRM project safely..."
    - mkdir -p /var/www/hrmsys4sbs_new
    - sudo chown -R gitlab-runner:gitlab-runner /var/www/hrmsys4sbs_new
    - sudo chmod -R 755 /var/www/hrmsys4sbs_new
    - rsync -av --ignore-errors ./ /var/www/hrmsys4sbs_new
  only:
    - main
