# Generated by Django 5.2.4 on 2025-12-19 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_advancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have hidden this ticket from their view', related_name='hidden_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
