# Generated by Django 5.2.4 on 2025-12-20 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ticket_hidden_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_group',
            field=models.BooleanField(default=False, help_text='True if this is a group chat message'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
