# Generated by Django 5.2.4 on 2025-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_ticket_options_ticket_end_date_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by admin (can be different from requested)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Requested amount', max_digits=12),
        ),
    ]
