# Generated by Django 5.2.4 on 2025-12-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_missing_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketfile',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketfile',
            name='uploaded_by',
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_aeffaf_idx',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='hidden_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tk_id',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='core.ticketreply'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('ticket', 'Ticket'), ('leave', 'Leave'), ('task', 'Task'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.DeleteModel(
            name='TicketFile',
        ),
    ]
