# Generated by Django 5.2.4 on 2025-12-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_ticketfile_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='reply',
        ),
        migrations.AddField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Expected completion date', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, help_text='Ticket subject', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tk_id',
            field=models.CharField(blank=True, help_text='Ticket ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_to', to='core.ticketreply'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('reopen', 'Reopen'), ('onhold', 'On Hold'), ('closed', 'Closed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
