# Generated by Django 5.2.4 on 2025-12-26 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_dashboardlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Work progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='Link this ticket to a task (admin choice)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.task'),
        ),
    ]
