# Generated by Django 5.2.4 on 2025-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_ticket_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='progress_locked',
            field=models.BooleanField(default=False, help_text='Lock progress at 100% to prevent further changes'),
        ),
    ]
