# Generated by Django 5.2.4 on 2025-12-31 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_assetfile_budgetexpensefile_budgetfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Attendance Log', 'verbose_name_plural': 'Attendance Logs'},
        ),
        migrations.AlterModelOptions(
            name='attendancemachine',
            options={'ordering': ['name', 'location'], 'verbose_name': 'Attendance Machine', 'verbose_name_plural': 'Attendance Machines'},
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Biometric machine that recorded this attendance (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='core.attendancemachine'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='machine_user_id',
            field=models.CharField(blank=True, help_text='User ID as stored in the biometric machine', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw data from machine/API for debugging'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for API-based machines', max_length=255),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='baud_rate',
            field=models.IntegerField(blank=True, default=9600, help_text='Baud rate for serial connection', null=True),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Additional machine-specific configuration (JSON format)'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description or notes'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message if sync failed'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='machine_type',
            field=models.CharField(choices=[('zkt', 'ZKTeco (ZKT K70, ZKT K40, etc.)'), ('realtime', 'RealTime'), ('biostar', 'BioStar'), ('hikvision', 'Hikvision'), ('dahua', 'Dahua'), ('attendance_pro', 'Attendance Pro'), ('generic_api', 'Generic API/Webhook'), ('custom', 'Custom/Other')], default='zkt', help_text='Brand/Type of biometric machine', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='password',
            field=models.CharField(blank=True, help_text='Password for machine authentication', max_length=100),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='protocol',
            field=models.CharField(choices=[('tcp_ip', 'TCP/IP'), ('http', 'HTTP'), ('https', 'HTTPS'), ('websocket', 'WebSocket'), ('serial', 'Serial/COM'), ('usb', 'USB')], default='tcp_ip', help_text='Connection protocol', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='serial_port',
            field=models.CharField(blank=True, help_text='COM port for serial connection (e.g., COM1, /dev/ttyUSB0)', max_length=50),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='sync_interval',
            field=models.IntegerField(default=15, help_text='Sync interval in minutes'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='url',
            field=models.URLField(blank=True, help_text='Full URL for HTTP/HTTPS/API connections', max_length=500),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='username',
            field=models.CharField(blank=True, help_text='Username for machine authentication', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='location',
            field=models.CharField(blank=True, help_text='Location where attendance was recorded', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('machine', 'Biometric Machine'), ('api', 'API/Webhook'), ('mobile', 'Mobile App'), ('web', 'Web Interface')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address for TCP/IP, HTTP, HTTPS, WebSocket', null=True),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this machine is active and should be synced'),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location of the machine', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='name',
            field=models.CharField(default='ZKT K70', help_text='Machine name/identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='port',
            field=models.IntegerField(blank=True, default=4370, help_text='Port number', null=True),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['machine', 'timestamp'], name='core_attend_machine_150a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['source', 'timestamp'], name='core_attend_source_bfcda5_idx'),
        ),
    ]
