# Generated by Django 5.2.4 on 2025-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_multi_biometric_machine_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Employee profile picture', null=True, upload_to='employee_profile_pictures/'),
        ),
    ]
