# Generated by Django 5.2.4 on 2026-01-01 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_profile_picture_to_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Company Admin user for this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this asset belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.company'),
        ),
        migrations.AddField(
            model_name='attendancemachine',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this machine belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_machines', to='core.company'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this budget belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.company'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this budget category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='core.company'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this department belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company'),
        ),
        migrations.AddField(
            model_name='designation',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this designation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='core.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this employee belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this holiday belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this project belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.company'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_new',
            field=models.ForeignKey(blank=True, help_text='Company this client belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.company'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('company', 'asset_id')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('company', 'name')},
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('employees', 'Employees Management'), ('attendance', 'Attendance Management'), ('leaves', 'Leave Management'), ('holidays', 'Holiday Management'), ('payroll', 'Payroll Management'), ('loans', 'Loan Management'), ('advances', 'Advance Requests'), ('projects', 'Project Management'), ('tasks', 'Task Management'), ('tickets', 'Ticket Management'), ('clients', 'Client Management'), ('budgets', 'Budget Management'), ('expenses', 'Expense Management'), ('revenues', 'Revenue Management'), ('assets', 'Asset Management'), ('invoices', 'Invoice Management'), ('estimates', 'Estimate Management'), ('reports', 'Reports & Analytics'), ('chat', 'Chat & Messaging'), ('notifications', 'Notifications'), ('settings', 'Settings'), ('marzi', 'Marzi Features')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this feature is available in the system')),
                ('companies', models.ManyToManyField(blank=True, help_text='Companies that have access to this feature', related_name='features', to='core.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company_admin', models.BooleanField(default=False, help_text='Whether this user is a Company Admin')),
                ('company', models.ForeignKey(blank=True, help_text='Company this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
