# Generated by Django 5.2.4 on 2026-01-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_migrate_client_company_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Client profile picture', null=True, upload_to='client_profile_pictures/'),
        ),
    ]
