# Generated by Django 5.2.4 on 2026-01-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_client_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizationsettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('PKR', 'Pakistani Rupee (₨)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('INR', 'Indian Rupee (₹)'), ('AED', 'UAE Dirham (د.إ)'), ('SAR', 'Saudi Riyal (﷼)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('SGD', 'Singapore Dollar (S$)'), ('MYR', 'Malaysian Ringgit (RM)'), ('THB', 'Thai Baht (฿)'), ('BHD', 'Bahraini Dinar (.د.ب)'), ('KWD', 'Kuwaiti Dinar (د.ك)'), ('OMR', 'Omani Rial (ر.ع.)'), ('QAR', 'Qatari Riyal (﷼)')], default='PKR', max_length=10),
        ),
    ]
