# Generated by Django 5.2.4 on 2026-01-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_update_currency_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo for payslips and documents', null=True, upload_to='company_logos/'),
        ),
    ]
