# Generated by Django 5.2.4 on 2026-01-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image_display_mode',
            field=models.CharField(choices=[('inline', 'Display as Image (Inline)'), ('link', 'Display as Link (Open in New Page)')], default='inline', help_text='How to display images: inline or as a link', max_length=10),
        ),
    ]
