# Generated by Django 5.2.4 on 2026-01-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_image_display_mode_to_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Enable email notifications'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_from_name',
            field=models.CharField(blank=True, default='HRM System', help_text="Name shown in 'From' field", max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Password for SMTP authentication', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='Email address for SMTP authentication', max_length=254),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL encryption'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption'),
        ),
    ]
