# Generated by Django 5.2.4 on 2026-01-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_companysettings_email_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, help_text='City where the employee is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email_from_name',
            field=models.CharField(blank=True, default='SBS Technologies HRM', help_text="Name shown in 'From' field", max_length=255),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email_host_user',
            field=models.EmailField(blank=True, default='technologiessbs15@gmail.com', help_text='Email address for SMTP authentication', max_length=254),
        ),
    ]
