# Generated by Django 5.2.4 on 2026-01-08 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_employee_city_alter_companysettings_email_from_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(help_text='Screenshot image', upload_to='employee_screenshots/')),
                ('captured_at', models.DateTimeField(auto_now_add=True, help_text='When the screenshot was captured')),
                ('date', models.DateField(help_text='Date of the screenshot')),
                ('is_active', models.BooleanField(default=True, help_text='Whether screenshot monitoring is active')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.employee')),
            ],
            options={
                'verbose_name': 'Employee Screenshot',
                'verbose_name_plural': 'Employee Screenshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='core_employ_employe_901b16_idx'), models.Index(fields=['employee', 'captured_at'], name='core_employ_employe_2181ff_idx'), models.Index(fields=['date'], name='core_employ_date_f50a16_idx')],
            },
        ),
    ]
